/**
 * Generate and download a DNA constraints analysis report as .txt
 * Used by both Upload and ViewFiles pages.
 */
export function downloadConstraintsReport(data, filename) {
  const s = data.summary || {};
  const frags = data.fragments || [];

  const lines = [
    "═══════════════════════════════════════════════════════",
    "  DNA VAULT — CONSTRAINT ANALYSIS REPORT",
    "═══════════════════════════════════════════════════════",
    "",
    `File ID:            ${data.file_id || "N/A"}`,
    `Encoding:           ${data.encoding_type || s.encoding_type || "N/A"}`,
    `Total Fragments:    ${data.total_fragments || s.total_fragments || frags.length}`,
    `Fragments Passing:  ${s.fragments_passing ?? "N/A"} / ${s.total_fragments ?? frags.length}`,
    `Pass Rate:          ${s.pass_rate ?? "N/A"}%`,
    "",
    "───────────────────────────────────────────────────────",
    "  SUMMARY",
    "───────────────────────────────────────────────────────",
    `Avg GC Content:         ${s.avg_gc_percent ?? "N/A"}%`,
    `Avg Melting Temp:       ${s.avg_melting_temp ?? "N/A"} °C`,
    `Total Homopolymers:     ${s.total_homopolymers ?? "N/A"}`,
    `Total Restriction Sites: ${s.total_restriction_sites ?? "N/A"}`,
    "",
    "───────────────────────────────────────────────────────",
    "  CONSTRAINT RULES",
    "───────────────────────────────────────────────────────",
    "GC Content:        35% – 65%            (synthesis stability)",
    "Homopolymer Max:   3 consecutive bases  (sequencing accuracy)",
    "Restriction Sites: 0 allowed            (prevents DNA cutting)",
    "Melting Temp:      50 – 80 °C           (PCR compatibility)",
    "Complexity:        >= 0.5               (k-mer diversity)",
    "",
    "───────────────────────────────────────────────────────",
    "  PER-FRAGMENT ANALYSIS",
    "───────────────────────────────────────────────────────",
    "",
    "Frag#  Length   GC%     Tm(°C)  HomoMax  Sites  Complex  Status",
    "─────  ──────   ─────   ──────  ───────  ─────  ───────  ──────",
  ];

  frags.forEach((f, i) => {
    const gc = f.gc_content?.percent ?? "?";
    const tm = f.melting_temp?.value_c ?? "?";
    const hm = f.homopolymers?.max_run ?? "?";
    const rs = f.restriction_sites?.count ?? "?";
    const cx = f.complexity?.value ?? "?";
    const pass = f.overall_pass ? "PASS" : "FAIL";
    const idx = String(i).padEnd(6);
    const len = String(f.length || "?").padEnd(8);
    const gcS = String(gc).padEnd(7);
    const tmS = String(tm).padEnd(7);
    const hmS = String(hm).padEnd(8);
    const rsS = String(rs).padEnd(6);
    const cxS = String(cx).padEnd(8);
    lines.push(`${idx} ${len} ${gcS} ${tmS} ${hmS} ${rsS} ${cxS} ${pass}`);
  });

  // Restriction site details
  const sitesFound = frags.filter(f => f.restriction_sites?.found?.length > 0);
  if (sitesFound.length > 0) {
    lines.push("");
    lines.push("───────────────────────────────────────────────────────");
    lines.push("  RESTRICTION SITES FOUND");
    lines.push("───────────────────────────────────────────────────────");
    sitesFound.forEach((f) => {
      f.restriction_sites.found.forEach(s => {
        lines.push(`  Fragment ${f.fragment_index ?? "?"}: ${s.enzyme} (${s.site}) at position ${s.position}`);
      });
    });
  }

  // Homopolymer details for failing fragments
  const homoFails = frags.filter(f => f.homopolymers?.max_run > 3);
  if (homoFails.length > 0) {
    lines.push("");
    lines.push("───────────────────────────────────────────────────────");
    lines.push("  HOMOPOLYMER VIOLATIONS");
    lines.push("───────────────────────────────────────────────────────");
    homoFails.forEach((f) => {
      (f.homopolymers.details || []).forEach(h => {
        if (h.length > 3) {
          lines.push(`  Fragment ${f.fragment_index ?? "?"}: ${h.base.repeat(h.length)} (${h.length}bp) at position ${h.position}`);
        }
      });
    });
  }

  lines.push("");
  lines.push("═══════════════════════════════════════════════════════");
  lines.push(`  Generated by DNA Vault — ${new Date().toISOString()}`);
  lines.push("═══════════════════════════════════════════════════════");

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename || "constraints"}_dna_report.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
